name: RGBdecryptoLENS
favicon: null
layout_spectrum: 0.75237
typography_spectrum: 0.9713859267067164
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ef0937'
    - '#0102fd'
    - '#0bf00a'
    - '#878787'
  brandStrength: 1
  lightness: 0.6171138850040734
  saturation: 0.40854283422231674
  rhythmicContrast: 0.8034076590556651
purpose: []
